[package]
name = "deduty_package_premier"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = '0.5'

deduty_package = { path = '../deduty_package' }
