[package]
name = "deduty_application_settings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xresult = { path = "../xresult" }

async-std = "1.12.0"
directories = "4.0.1"
