[package]
name = "deduty_package_serde"
version = "0.1.0"
edition = "2021"

[dependencies]
deduty_package_traits = { path = "../deduty_package_traits" }
xresult = { path = "../xresult" }

serde = { version = "1.0", features = ["derive"] }
