// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddPackage: typeof import('./components/AddPackage/AddPackage.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CreatePackage: typeof import('./components/AddPackage/CreatePackage.vue')['default']
    Error: typeof import('./components/Error.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GitPackage: typeof import('./components/AddPackage/GitPackage.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    LocalPackage: typeof import('./components/AddPackage/LocalPackage.vue')['default']
    PackageBar: typeof import('./components/PackageBar/PackageBar.vue')['default']
    PackageForm: typeof import('./components/PackageBar/PackageForm/PackageForm.vue')['default']
    PackageFormAbout: typeof import('./components/PackageBar/PackageForm/PackageFormAbout.vue')['default']
    PackageFormMenu: typeof import('./components/PackageBar/PackageForm/PackageFormMenu.vue')['default']
    PackageItem: typeof import('./components/PackageBar/PackageList/PackageItem.vue')['default']
    PackageList: typeof import('./components/PackageBar/PackageList/PackageList.vue')['default']
    PackageMenu: typeof import('./components/PackageBar/PackageMenu/PackageMenu.vue')['default']
    PackageMenuAboutContent: typeof import('./components/PackageBar/PackageForm/PackageMenuAboutContent.vue')['default']
    PackageSearch: typeof import('./components/PackageBar/PackageSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
