// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DirectoryPathRequirement: typeof import('./components/PackageRequirements/DirectoryPathRequirement.vue')['default']
    Error: typeof import('./components/Error.vue')['default']
    LectionItem: typeof import('./components/LectionList/LectionItem.vue')['default']
    LectionList: typeof import('./components/LectionList/LectionList.vue')['default']
    LectionReader: typeof import('./components/LectionReader.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    PackageAdd: typeof import('./components/PackageAdd/PackageAdd.vue')['default']
    PackageAddSuspense: typeof import('./components/PackageAdd/PackageAddSuspense.vue')['default']
    PackageForm: typeof import('./components/PackageForm/PackageForm.vue')['default']
    PackageFormAbout: typeof import('./components/PackageForm/PackageFormAbout.vue')['default']
    PackageFormMenu: typeof import('./components/PackageForm/PackageFormMenu.vue')['default']
    PackageFormMeta: typeof import('./components/PackageForm/PackageFormMeta.vue')['default']
    PackageFormSettings: typeof import('./components/PackageForm/PackageFormSettings/PackageFormSettings.vue')['default']
    PackageFormSettingsUpdate: typeof import('./components/PackageForm/PackageFormSettings/PackageFormSettingsUpdate.vue')['default']
    PackageItem: typeof import('./components/PackageList/PackageItem.vue')['default']
    PackageList: typeof import('./components/PackageList/PackageList.vue')['default']
    PackageRequirements: typeof import('./components/PackageRequirements/PackageRequirements.vue')['default']
    PackageUpdate: typeof import('./components/PackageUpdate/PackageUpdate.vue')['default']
    PackageUpdateSuspense: typeof import('./components/PackageUpdate/PackageUpdateSuspense.vue')['default']
    Reader: typeof import('./components/Reader/Reader.vue')['default']
    ReaderHtmlComponent: typeof import('./components/Reader/ReaderHtmlComponent.vue')['default']
    ReaderImageComponent: typeof import('./components/Reader/ReaderImageComponent.vue')['default']
    ReaderMarkdownComponent: typeof import('./components/Reader/ReaderMarkdownComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
