[package]
name = "deduty_package"
version = "0.2.0"
edition = "2021"

[dependencies]
xresult = { path = "../xresult" }

async-std = "1.12.0"
async-trait = "0.1.58"
serde = { version = "1.0", features = ["derive"] }
uuid = "1.2.2"
